### ISSUE TITLE
Unclear license

### ISSUE THREAD

**Issue by hfiguiere** [Lswbanban/BlueBrick#6]
The license is unclear.

It say it is GPL-3. That's clear.
But it says in the README: "You can use it for your personnal purpose but not for commercial profit." which is against the GPL-3 license.

So which is it?

**Comment by Lswbanban** [comment]
It is GPL-3.
I've updated the wording in the README, this sentence was from a previous old version of the readme.
Sorry for the confusion.

**Comment by matteason** [comment]
@Lswbanban Just a heads up, the commercial profit restriction still appears on the homepage at https://bluebrick.lswproject.com/ and on the start page of the documentation on that site
